let StudentDetails=
[
    {
        sid:1,
        sname:"ABC1",
        sage:25
    },{
        sid:2,
        sname:"ABC2",
        sage:25
    },{
        sid:3,
        sname:"ABC3",
        sage:25
    },{
        sid:4,
        sname:"ABC4",
        sage:25
    },{
        sid:5,
        sname:"ABC5",
        sage:25
    },{
        sid:6,
        sname:"ABC6",
        sage:25
    },{
        sid:7,
        sname:"ABC7",
        sage:25
    },{
        sid:8,
        sname:"ABC8",
        sage:25
    },
    {
        sid:9,
        sname:"ABC8",
        sage:25
    },{
        sid:10,
        sname:"ABC8",
        sage:25
    },{
        sid:11,
        sname:"ABC8",
        sage:25
    },{
        sid:12,
        sname:"ABC8",
        sage:25
    },{
        sid:13,
        sname:"ABC8",
        sage:25
    },{
        sid:14,
        sname:"ABC8",
        sage:25
    }
]
export default StudentDetails;